package audit

import (
	"encoding/json"
	"os"
	"path/filepath"
	"testing"

	"github.com/local/srxtool-go/internal/config"
)

const fixtures = "../../testdata/fixtures"
const golden = "../../testdata/golden"

// Note on testdata/golden/audit-*.json: originally generated from the
// reference Python (srxaudit.py) for parity verification (task 09). After
// translating the finding text in checks_policy_zone.go/checks_system.go
// to English (backlog item 3, English pass), these 4 fixtures were
// regenerated from this package's own translated output rather than from
// Python — Python's srxaudit.py stays French (it's the parity oracle, not
// the shipped product) so a byte-for-byte match is no longer meaningful
// past this point. TestGoldenAuditAllFixtures below now guards against
// regressions in the Go implementation itself (same checks trigger, same
// structure), not against textual drift from Python.

func mustModel(t *testing.T, name string) *config.Model {
	t.Helper()
	data, err := os.ReadFile(filepath.Join(fixtures, name))
	if err != nil {
		t.Fatalf("unreadable fixture: %v", err)
	}
	m, err := config.Parse(data, config.Options{})
	if err != nil {
		t.Fatalf("parsing failed: %v", err)
	}
	return m
}

// TestGoldenAuditAllFixtures is task 03's central regression test:
// set-based AND field-by-field comparison against the reference Python, on
// the 4 fixtures (goldens regenerated by scripts/gen_golden_audit.py).
func TestGoldenAuditAllFixtures(t *testing.T) {
	for _, name := range []string{
		"sample.xml", "sample2.txt", "sample-show-config.txt", "sample-display-set.txt",
	} {
		t.Run(name, func(t *testing.T) {
			m := mustModel(t, name)
			findings, err := Run(m)
			if err != nil {
				t.Fatalf("Run: %v", err)
			}
			gotBytes, err := FindingsJSON(findings)
			if err != nil {
				t.Fatalf("FindingsJSON: %v", err)
			}
			wantBytes, err := os.ReadFile(filepath.Join(golden, "audit-"+name+".json"))
			if err != nil {
				t.Fatalf("unreadable golden: %v", err)
			}

			var got, want struct {
				Summary  map[string]int   `json:"summary"`
				Findings []map[string]any `json:"findings"`
			}
			if err := json.Unmarshal(gotBytes, &got); err != nil {
				t.Fatalf("Go re-read: %v", err)
			}
			if err := json.Unmarshal(wantBytes, &want); err != nil {
				t.Fatalf("golden re-read: %v", err)
			}

			if len(got.Findings) != len(want.Findings) {
				t.Fatalf("%d Go findings vs %d expected", len(got.Findings), len(want.Findings))
			}
			key := func(f map[string]any) string {
				return f["severity"].(string) + "|" + f["check"].(string) + "|" + f["where"].(string)
			}
			gm := map[string]map[string]any{}
			for _, f := range got.Findings {
				gm[key(f)] = f
			}
			for _, wf := range want.Findings {
				k := key(wf)
				gf, ok := gm[k]
				if !ok {
					t.Errorf("finding missing on the Go side: %s", k)
					continue
				}
				for _, field := range []string{"title", "recommendation", "reference", "fix"} {
					gv, _ := json.Marshal(gf[field])
					wv, _ := json.Marshal(wf[field])
					if string(gv) != string(wv) {
						t.Errorf("%s / field %q mismatch:\n go   %s\n want %s", k, field, gv, wv)
					}
				}
			}
			for sev, n := range want.Summary {
				if got.Summary[sev] != n {
					t.Errorf("summary[%s] = %d, expected %d", sev, got.Summary[sev], n)
				}
			}
		})
	}
}

// TestSortOrder checks the sort order (severity, then check, then
// location) on a fixture that produces several findings of different
// severities.
func TestSortOrder(t *testing.T) {
	m := mustModel(t, "sample-show-config.txt")
	findings, err := Run(m)
	if err != nil {
		t.Fatal(err)
	}
	for i := 1; i < len(findings); i++ {
		a, b := findings[i-1], findings[i]
		ra, rb := severityRank[a.Severity], severityRank[b.Severity]
		if ra > rb {
			t.Fatalf("severity sort broken between %v and %v", a, b)
		}
		if ra == rb && a.Check > b.Check {
			t.Fatalf("check sort broken between %v and %v", a, b)
		}
	}
}

// TestMinSeverityFilter: the filter keeps CRITICAL/HIGH and excludes the
// rest when min=HIGH.
func TestMinSeverityFilter(t *testing.T) {
	m := mustModel(t, "sample-show-config.txt")
	findings, err := Run(m)
	if err != nil {
		t.Fatal(err)
	}
	filtered := FilterMinSeverity(findings, High)
	for _, f := range filtered {
		if f.Severity != Critical && f.Severity != High {
			t.Errorf("severity %s should not pass the HIGH filter", f.Severity)
		}
	}
	if len(filtered) >= len(findings) {
		t.Fatal("the filter should exclude at least one finding on this fixture")
	}
}

// TestSystemAbsentSkipsSNMPToo: reproduces the Python behavior where
// SNMP-* checks are skipped if `system {}` is absent, even if `snmp {}`
// exists. Behavior kept as-is (see report.go, Run's comment).
func TestSystemAbsentSkipsSNMPToo(t *testing.T) {
	conf := `snmp {
    community public {
        authorization read-write;
    }
}
security {
    zones {
        security-zone trust {
            interfaces { ge-0/0/0.0; }
        }
    }
}
`
	m, err := config.Parse([]byte(conf), config.Options{})
	if err != nil {
		t.Fatalf("parsing: %v", err)
	}
	findings, err := Run(m)
	if err != nil {
		t.Fatalf("Run: %v", err)
	}
	for _, f := range findings {
		if f.Check == "SNMP-DEFAULT-COMM" || f.Check == "SNMP-RW" || f.Check == "SNMP-NO-V3" {
			t.Fatalf("an SNMP-* finding was produced while system{} is absent: %v", f)
		}
	}
}

// TestSystemPresentEnablesSNMP: conversely, as soon as system{} exists
// (even empty of services), the SNMP-* checks become active again.
func TestSystemPresentEnablesSNMP(t *testing.T) {
	conf := `system {
    host-name fw1;
}
snmp {
    community public {
        authorization read-write;
    }
}
`
	m, err := config.Parse([]byte(conf), config.Options{AllowEmpty: true})
	if err != nil {
		t.Fatalf("parsing: %v", err)
	}
	findings, err := Run(m)
	if err != nil {
		t.Fatalf("Run: %v", err)
	}
	found := map[string]bool{}
	for _, f := range findings {
		found[f.Check] = true
	}
	for _, want := range []string{"SNMP-DEFAULT-COMM", "SNMP-RW"} {
		if !found[want] {
			t.Errorf("expected finding %s, missing", want)
		}
	}
}

// TestExternalZoneHintCaseSensitive: reproduces the Python behavior,
// case-sensitive ("Untrust" doesn't match "untrust").
func TestExternalZoneHintCaseSensitive(t *testing.T) {
	conf := `security {
    zones {
        security-zone Untrust {
            interfaces {
                ge-0/0/0.0;
            }
        }
    }
}
`
	m, err := config.Parse([]byte(conf), config.Options{AllowEmpty: true})
	if err != nil {
		t.Fatalf("parsing: %v", err)
	}
	findings, err := Run(m)
	if err != nil {
		t.Fatalf("Run: %v", err)
	}
	for _, f := range findings {
		if f.Check == "ZONE-NO-SCREEN" {
			t.Fatal("ZONE-NO-SCREEN (external variant) should not trigger " +
				"for an 'Untrust' zone (capitalized): EXTERNAL_ZONE_HINT is case-sensitive")
		}
	}
	// It should still trigger the internal variant (no public interface,
	// no screen).
	hasInt := false
	for _, f := range findings {
		if f.Check == "ZONE-NO-SCREEN-INT" {
			hasInt = true
		}
	}
	if !hasInt {
		t.Fatal("expected ZONE-NO-SCREEN-INT for a zone considered internal")
	}
}

// TestUnsafeNameAborts: a policy name containing an injection character
// must abort Run() entirely, not produce a dangerous fix.
func TestUnsafeNameAborts(t *testing.T) {
	m := &config.Model{
		Zones: map[string]config.Zone{},
		Policies: []config.Policy{{
			FromZone: "trust", ToZone: "untrust", Name: "bad;name",
			Source: []string{"any"}, Destination: []string{"any"},
			Application: []string{"any"}, Action: "permit",
		}},
	}
	_, err := Run(m)
	if err == nil {
		t.Fatal("expected an error for a dangerous policy name")
	}
}

func TestFixTextAndReportTextNonEmpty(t *testing.T) {
	m := mustModel(t, "sample-show-config.txt")
	findings, err := Run(m)
	if err != nil {
		t.Fatal(err)
	}
	if fix := FixText(findings); len(fix) == 0 || !contains(fix, "proposed fixes") {
		t.Error("FixText: expected header missing")
	}
	if report := ReportText(findings, m); !contains(report, "SRX HARDENING AUDIT") ||
		!contains(report, "Detected source format: curly") {
		t.Error("ReportText: expected structure missing")
	}
}

func contains(s, sub string) bool {
	for i := 0; i+len(sub) <= len(s); i++ {
		if s[i:i+len(sub)] == sub {
			return true
		}
	}
	return false
}
