package config

import (
	"encoding/json"
	"fmt"
	"reflect"
	"sort"
	"strings"
	"testing"
)

// TestGoldenModelAllFixtures is task 01's central regression test: the
// model produced by Go must be STRICTLY identical to the one produced by
// the reference Python implementation on the same fixtures, field by
// field, warnings included.
//
// The golden files are regenerated by scripts/gen_golden_model.py.
//
// Comparison goes through map[string]any rather than raw bytes: the only
// accepted gap with Python is JSON key order (Go sorts map keys, Python
// preserves insertion order). That's task 01's only deliberate divergence
// — to report in the MD 09 table.
//
// Backlog-mandated exception: the parser's user-facing warning strings
// were translated from French to English (task 03, full English
// translation of srxtool-go). testdata/golden/model-sample2.txt.json's
// "warnings" field was updated to the new English text to match; this is
// no longer byte-parity with the French Python oracle, only structural
// parity, which is expected and intentional going forward.
func TestGoldenModelAllFixtures(t *testing.T) {
	for _, name := range []string{
		"sample.xml",
		"sample2.txt",
		"sample-show-config.txt",
		"sample-display-set.txt",
	} {
		t.Run(name, func(t *testing.T) {
			m := mustParse(t, name)

			goJSON, err := json.Marshal(m)
			if err != nil {
				t.Fatalf("encoding the Go model: %v", err)
			}
			var got, want map[string]any
			if err := json.Unmarshal(goJSON, &got); err != nil {
				t.Fatalf("re-reading the Go model: %v", err)
			}
			if err := json.Unmarshal(read(t, golden, "model-"+name+".json"), &want); err != nil {
				t.Fatalf("unreadable golden: %v", err)
			}

			for _, key := range sortedMapKeys(want) {
				if !reflect.DeepEqual(got[key], want[key]) {
					t.Errorf("field %q mismatch:\n  Go     : %s\n  Python : %s",
						key, compact(got[key]), compact(want[key]))
				}
			}
			for _, key := range sortedMapKeys(got) {
				if _, ok := want[key]; !ok {
					t.Errorf("field %q present on the Go side, absent from the Python golden", key)
				}
			}
		})
	}
}

func sortedMapKeys(m map[string]any) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}

func compact(v any) string {
	b, err := json.Marshal(v)
	if err != nil {
		return fmt.Sprintf("%v", v)
	}
	s := string(b)
	if len(s) > 600 {
		s = s[:600] + "…"
	}
	return strings.ReplaceAll(s, `\u003e`, ">")
}
